name: Map
version: @version@
main: net.arcticforestmc.map.Map
commands:
  map:
    description: Sends who made the world to the player and which world the player is in.
    aliases: [whatsthisspawn, whobuiltthis, whobuilt, builtby, buildmadeby]
  mapreload:
    description: Reloads the config.yml file
